# Generated by Django 3.0.4 on 2020-03-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyShopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='publish_date',
            new_name='pub_date',
        ),
    ]
